### ISSUE TITLE
Sync nullable attributes with Cluster API

### ISSUE THREAD

**Issue by WilliamDEdwards** [CyberfusionIO/cyberfusion-cluster-api-client#7]
The attributes that are marked as nullable and non-nullable are out of sync between the Cluster API and the client. Every attribute should be checked and updated if needed.

**Comment by dvdheiden** [comment]
To fully match the objects in the Cluster API, we could consider using the create/update models from the Cluster API. Right now, the models in this package represent the entity (i.e. VirtualHost) used for all CRUD actions.

**Comment by WilliamDEdwards** [comment]
When doing the major version increase, change all references to _Cluster API_ to _Core API_ (what I wanted to do in https://github.com/CyberfusionIO/cyberfusion-cluster-api-client/pull/114).

**Comment by WilliamDEdwards** [comment]
Will be automatically fixed by https://github.com/CyberfusionIO/cyberfusion-cluster-api-client/issues/117
