### ISSUE TITLE
Optimizing enabled / Backups enabled

### ISSUE THREAD

**Issue by mbardelmeijer** [CyberfusionIO/cyberfusion-cluster-api-client#72]
## Describe the bug

When calling the `databases` create call, the call fails as the `optimizing_enabled` and `backups_enabled` fields are required. These are available on the model level, however not passed trough in the `Databases` endpoint.

## Reproduction

Create a database via the `create` API call

## Expected behavior

The database to be created.

## Actual behavior

API failure:
```
{
"loc": [
"body",
"optimizing_enabled"
],
"msg": "field required",
"type": "value_error.missing"
},
{
"loc": [
"body",
"backups_enabled"
],
"msg": "field required",
"type": "value_error.missing"
}
```

## Additional information

-

**Comment by dvdheiden** [comment]
Fix released in 1.101.2.
